
[package]
name = "tokengiver"
version = "0.1.0"
edition = "2023_10"
cairo-version = "2.8.2"
scarb-version = "2.8.2"
authors = ["Oshioke Salaki & Stephanie Egbuonu"]
description = "Decentralized Charity Dapp"
keywords = ["SocialFi", "tokenbound", "cairo", "contracts", "starknet"]

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.8.2"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.15.0" }
token_bound_accounts= { git = "https://github.com/Starknet-Africa-Edu/TBA", tag = "v0.3.0" }

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.31.0" }

[[target.starknet-contract]]
casm = true
sierra = true